timezone: Europe/Moscow
hibernate:
  dialect: org.hibernate.dialect.PostgreSQL95Dialect
datasource:
  url: jdbc:postgresql://localhost:5432/library
  username: postgres
  password: "0000"

student:
  name: Egor
  last_name: Paramoshkin
  group: IKBO-10-19
  var: "Variant 3"

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
