timezone: Europe/Moscow
hibernate:
  dialect: org.hibernate.dialect.PostgreSQL95Dialect
datasource:
  url: jdbc:postgresql://localhost:5432/library
  username: postgres
  password: "0000"

student:
  name: Egor
  last_name: Paramoshkin
  group: IKBO-10-19
  var: "Variant 3"

scan:
  dir: "com.redbird.lesson17.models"
